### ISSUE TITLE
Title Colors in the Release Notes page are hard to read

### ISSUE THREAD

**Issue by jonasbb** [wheredoesyourmindgo/harmonized-vscode-theme#2]
The colors in the release notes page are quite hard to read, especially the second title, as they are very thin and low contrast to the background, especially the "More prominent pinned tabs". The built-in Solarized Light theme uses a darker font color. 

Harmonized Theme
![Screenshot from 2020-11-06 11-14-39](https://user-images.githubusercontent.com/273459/98357872-2239ee00-2026-11eb-9d12-8f70fa5fe4ef.png)

Built-in Solarized Light Theme
![Screenshot from 2020-11-06 11-14-59](https://user-images.githubusercontent.com/273459/98357876-2403b180-2026-11eb-9d90-aa81891be375.png)

**Comment by pcwa-ahendricks** [comment]
Thanks for letting me know. Should be fixed now.

**Comment by jonasbb** [comment]
Thank you very much 🙂
