### ISSUE TITLE
Inline hints have a very low color contrast

### ISSUE THREAD

**Issue by jonasbb** [wheredoesyourmindgo/harmonized-vscode-theme#6]
Harmonized Light (0.5.7):
![Screenshot from 2022-03-08 09-07-28](https://user-images.githubusercontent.com/273459/157195906-0b398e56-3e90-452e-add5-c7f31c7fbd27.png)

Solarized Light:
![Screenshot from 2022-03-08 09-21-01](https://user-images.githubusercontent.com/273459/157195909-233274b4-6594-4ed7-89c5-1920bdb1c101.png)

I tested the inline hints with the current pre-release version of rust-analyzer. The harmonized colors have a low contrast (1.2:1) with the text being #F9F1D9 and the background #ECDCAD. I find the dark font in the default solarized theme more readable.

**Comment by wheredoesyourmindgo** [comment]
what file type is that, .rs? are you using any vscode extensions that i should be aware of in order to debug this (ex. rust-analyzer extension)? thanks for the issue and letting me know.

**Comment by jonasbb** [comment]
Yes, the screenshots are Rust with rust-analyzer. You do not need any extra extensions though, the built-in extensions of 1.65 are enough. Writing this snippet in a Javascript file and setting `javascript.inlayHints.enumMemberValues.enabled` enables inlay hints for me too.

```javascript
enum MyValue {
    A,
    B,
}
```

**Comment by jonasbb** [comment]
Thanks for the quick help :)
